queue_rules:
  - name: default
    conditions:
      - check-success=build
      - -label~=(do-not-merge)
pull_request_rules:
  - name: Automatic merge on approval and successful build
    actions:
      review:
        type: APPROVE
        message: Automatically approving reference docs
      delete_head_branch: {}
      queue:
        method: squash
        name: default
        commit_message_template: |-
          {{ title }} (#{{ number }})
          {{ body }}
    conditions:
      - author=monadabot
      - or:
          - files~=docs/reference/WingSDK.md
          - files~=docs/reference/WingConsole.md
      - files~=docs/reference/previous_versions/(WingSDK|WingConsole)/
      - check-success=build
