queue_rules:
  - name: default
    conditions:
      - status-success=build
      - status-success=Vercel
      - -label~=(do-not-merge)
pull_request_rules:
  - name: Automatic merge on approval and successful build
    actions:
      delete_head_branch: {}
      queue:
        method: squash
        name: default
        commit_message_template: |-
          {{ title }} (#{{ number }})

          {{ body }}
    conditions:
      - "#approved-reviews-by>=1"
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=Vercel
      - -merged
      - -closed
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
  - name: Automatic merge on successful docsite update from bot
    actions:
      delete_head_branch: {}
      queue:
        method: squash
        name: default
        commit_message_template: |-
          {{ title }} (#{{ number }})

          {{ body }}
    conditions:
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=Vercel
      - author=monadabot
      - -merged
      - -closed
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
