/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
/*
  mainSidebar: [
    {
      type: 'doc',
      id: 'getting-started',
    },

    {
    type: "category",
    label: 'Previous Versions',
    collapsible: true,
    collapsed: true,
    items: [
      {
        type: "doc",
        id: "reference/previous_versions/WingSDK/1.2.0",
      },
      {
        type: "doc",
        id: "reference/previous_versions/WingSDK/1.1.39",
      }
    ]
  }]
*/
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
