// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for PackagePublishWebhookFunction
 */
export interface PackagePublishWebhookFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/constructs/PackagePublishWebhook/PackagePublishWebhook.
 */
export class PackagePublishWebhookFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: PackagePublishWebhookFunctionProps) {
    super(scope, id, {
      description: 'src/constructs/PackagePublishWebhook/PackagePublishWebhook.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs14.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/constructs/PackagePublishWebhook/PackagePublishWebhook.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}